// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const AbilitySchema = z
    .enum([
        CONSTS.ABILITY_STRENGTH,
        CONSTS.ABILITY_DEXTERITY,
        CONSTS.ABILITY_CONSTITUTION,
        CONSTS.ABILITY_INTELLIGENCE,
        CONSTS.ABILITY_WISDOM,
        CONSTS.ABILITY_CHARISMA,
    ])
    .describe('fields.ability');

export type Ability = z.infer<typeof AbilitySchema>;
