// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const AdvantageSchema = z
    .enum([
        CONSTS.ADV_ATTACK_ROLL_PROPERTY_EFFECT,
        CONSTS.ADV_ATTACK_ROLL_TARGET_DISABLED,
        CONSTS.ADV_ATTACK_ROLL_TARGET_RESTRAINED,
        CONSTS.ADV_ATTACK_ROLL_UNDETECTED_BY_TARGET,
    ])
    .describe('fields.advantage');

export type Advantage = z.infer<typeof AdvantageSchema>;
