// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const AilmentSchema = z
    .enum([
        CONSTS.AILMENT_ABILITY_DRAIN,
        CONSTS.AILMENT_ATTACK_DRAIN,
        CONSTS.AILMENT_ARMOR_CLASS_DRAIN,
        CONSTS.AILMENT_BLINDNESS,
        CONSTS.AILMENT_DISEASE,
        CONSTS.AILMENT_DOOM,
        CONSTS.AILMENT_FEAR,
        CONSTS.AILMENT_LEVEL_DRAIN,
        CONSTS.AILMENT_POISON,
        CONSTS.AILMENT_PARALYSIS,
        CONSTS.AILMENT_PETRIFICATION,
        CONSTS.AILMENT_SILENCE,
        CONSTS.AILMENT_SLOW,
        CONSTS.AILMENT_STUN,
    ])
    .describe('fields.ailment');

export type Ailment = z.infer<typeof AilmentSchema>;
