// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const CapabilitySchema = z
    .enum([
        CONSTS.CAPABILITY_ACT,
        CONSTS.CAPABILITY_SEE,
        CONSTS.CAPABILITY_FIGHT,
        CONSTS.CAPABILITY_CAST_SELF,
        CONSTS.CAPABILITY_CAST_TARGET,
        CONSTS.CAPABILITY_MOVE,
        CONSTS.CAPABILITY_SWIM,
    ])
    .describe('fields.capability');

export type Capability = z.infer<typeof CapabilitySchema>;
