// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const DisadvantageSchema = z
    .enum([
        CONSTS.DIS_ATTACK_ROLL_BAD_EQUIPMENT,
        CONSTS.DIS_ATTACK_ROLL_FRIGHTENED,
        CONSTS.DIS_ATTACK_ROLL_POISONED,
        CONSTS.DIS_ATTACK_ROLL_PROPERTY_EFFECT,
        CONSTS.DIS_ATTACK_ROLL_RESTRAINED,
        CONSTS.DIS_ATTACK_ROLL_TARGET_PROTECTED,
        CONSTS.DIS_ATTACK_ROLL_TARGET_UNDETECTED,
        CONSTS.DIS_ATTACK_ROLL_WINDY_ENVIRONMENT,
        CONSTS.ADV_SAVING_THROW_PROPERTY_EFFECT,
        CONSTS.DIS_SAVING_THROW_IMPEDED_MOBILITY,
        CONSTS.DIS_SAVING_THROW_PROPERTY_EFFECT,
    ])
    .describe('fields.disadvantage');

export type Disadvantage = z.infer<typeof DisadvantageSchema>;
