// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const EntityTypeSchema = z
    .enum([
        CONSTS.ENTITY_TYPE_CREATURE,
        CONSTS.ENTITY_TYPE_ITEM,
        CONSTS.ENTITY_TYPE_EXTENDED_PROPERTIES,
    ])
    .describe('fields.entityType');

export type EntityType = z.infer<typeof EntityTypeSchema>;
