// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const FeatTypeSchema = z
    .enum([
        CONSTS.FEAT_ACTION_SURGE_2,
        CONSTS.FEAT_ACTION_SURGE,
        CONSTS.FEAT_EXTRA_ATTACK_1,
        CONSTS.FEAT_EXTRA_ATTACK_2,
        CONSTS.FEAT_EXTRA_ATTACK_3,
        CONSTS.FEAT_FIGHTING_STYLE_ARCHERY,
        CONSTS.FEAT_FIGHTING_STYLE_DEFENSE,
        CONSTS.FEAT_FIGHTING_STYLE_DUELLING,
        CONSTS.FEAT_FIGHTING_STYLE_GREAT_WEAPON,
        CONSTS.FEAT_IMPROVED_CRITICAL,
        CONSTS.FEAT_REMARKABLE_ATHLETE,
        CONSTS.FEAT_SECOND_WIND,
        CONSTS.FEAT_SUPERIOR_CRITICAL,
        CONSTS.FEAT_SURVIVOR,
    ])
    .describe('fields.featType');

export type FeatType = z.infer<typeof FeatTypeSchema>;
