import z from 'zod';
import CONSTS from '../../consts';

export const ImmunitySchema = z
    .enum([
        CONSTS.IMMUNITY_TYPE_ABILITY_DECREASE,
        CONSTS.IMMUNITY_TYPE_AC_DECREASE,
        CONSTS.IMMUNITY_TYPE_ATTACK_DECREASE,
        CONSTS.IMMUNITY_TYPE_BLINDNESS,
        CONSTS.IMMUNITY_TYPE_CHARM,
        CONSTS.IMMUNITY_TYPE_CRITICAL_HIT,
        CONSTS.IMMUNITY_TYPE_DAMAGE_DECREASE,
        CONSTS.IMMUNITY_TYPE_DEATH,
        CONSTS.IMMUNITY_TYPE_DISEASE,
        CONSTS.IMMUNITY_TYPE_FEAR,
        CONSTS.IMMUNITY_TYPE_ROOT,
        CONSTS.IMMUNITY_TYPE_NEGATIVE_LEVEL,
        CONSTS.IMMUNITY_TYPE_PARALYSIS,
        CONSTS.IMMUNITY_TYPE_PETRIFICATION,
        CONSTS.IMMUNITY_TYPE_POISON,
        CONSTS.IMMUNITY_TYPE_SAVING_THROW_DECREASE,
        CONSTS.IMMUNITY_TYPE_SLOW,
        CONSTS.IMMUNITY_TYPE_SNEAK_ATTACK,
        CONSTS.IMMUNITY_TYPE_STUN,
    ])
    .describe('fields.immunity');

export type Immunity = z.infer<typeof ImmunitySchema>;
