import z from 'zod';
import { CONSTS } from '../../consts';

export const PropertyTypeSchema = z
    .enum([
        CONSTS.PROPERTY_ABILITY_CHECK_MODIFIER,
        CONSTS.PROPERTY_ABILITY_MODIFIER,
        CONSTS.PROPERTY_ADVANTAGE_ATTACK,
        CONSTS.PROPERTY_ADVANTAGE_SAVING_THROW,
        CONSTS.PROPERTY_ARMOR_CLASS_MODIFIER,
        CONSTS.PROPERTY_ATTACK_COUNT_MODIFIER,
        CONSTS.PROPERTY_ATTACK_MODIFIER,
        CONSTS.PROPERTY_CRITICAL_RANGE_MODIFIER,
        CONSTS.PROPERTY_CURSED,
        CONSTS.PROPERTY_DAMAGE_IMMUNITY,
        CONSTS.PROPERTY_DAMAGE_MODIFIER,
        CONSTS.PROPERTY_DAMAGE_REDUCTION,
        CONSTS.PROPERTY_DAMAGE_RESISTANCE,
        CONSTS.PROPERTY_DAMAGE_VULNERABILITY,
        CONSTS.PROPERTY_DARKVISION,
        CONSTS.PROPERTY_DISADVANTAGE_ATTACK,
        CONSTS.PROPERTY_DISADVANTAGE_SAVING_THROW,
        CONSTS.PROPERTY_ENFEEBLEMENT,
        CONSTS.PROPERTY_EXTRA_HITPOINTS,
        CONSTS.PROPERTY_EXTRA_WEAPON_DAMAGE_TYPE,
        CONSTS.PROPERTY_FEAT,
        CONSTS.PROPERTY_HEALING_FACTOR,
        CONSTS.PROPERTY_HEALING_MODIFIER,
        CONSTS.PROPERTY_IMMUNITY,
        CONSTS.PROPERTY_LIGHT,
        CONSTS.PROPERTY_MAX_DEXTERITY_BONUS,
        CONSTS.PROPERTY_MULTI_ATTACK,
        CONSTS.PROPERTY_ON_ATTACK_HIT,
        CONSTS.PROPERTY_PROTECTION_FROM_SPECIES,
        CONSTS.PROPERTY_REGENERATION,
        CONSTS.PROPERTY_SAVING_THROW_MODIFIER,
        CONSTS.PROPERTY_SKILL_MODIFIER,
        CONSTS.PROPERTY_SNEAK_ATTACK,
        CONSTS.PROPERTY_SPEED_FACTOR,
        CONSTS.PROPERTY_SPELL_POWER,
        CONSTS.PROPERTY_SPIKE_DAMAGE,
        CONSTS.PROPERTY_THINKER,
        CONSTS.PROPERTY_UNIDENTIFIED,
        CONSTS.PROPERTY_VAMPYRE,
        CONSTS.PROPERTY_WEIGHT_FACTOR,
    ])
    .describe('fields.property');

export type PropertyType = z.infer<typeof PropertyTypeSchema>;
