// File generated by build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const RollTypeSchema = z
    .enum([
        CONSTS.ROLL_TYPE_ATTACK,
        CONSTS.ROLL_TYPE_SAVING_THROW,
        CONSTS.ROLL_TYPE_SKILL_CHECK,
    ])
    .describe('fields.rollType');

export type RollType = z.infer<typeof RollTypeSchema>;
