// File generated by /home/ralphy/projects/o876-battle-system-ts/bin/build-enum-schema

import z from 'zod';
import { CONSTS } from '../../consts';

export const RollTypeSchema = z
    .enum([
        CONSTS.ROLL_TYPE_ATTACK_ROLL,
        CONSTS.ROLL_TYPE_SAVING_THROW,
        CONSTS.ROLL_TYPE_SKILL_CHECK,
    ])
    .describe('fields.rollType');

export type RollType = z.infer<typeof RollTypeSchema>;
