// File generated by /home/ralphy/projects/o876-battle-system-ts/bin/build-getters-index
import { ReactiveStore } from '@laboralphy/reactor';
import { State } from './state';

import { getDefensiveSlots } from './getters/getDefensiveSlots';
import { getEquipmentProperties } from './getters/getEquipmentProperties';
import { getEquipmentSlotProperties } from './getters/getEquipmentSlotProperties';
import { getInnateProperties } from './getters/getInnateProperties';
import { getOffensiveSlots } from './getters/getOffensiveSlots';
import { getSelectedWeaponAttributeSet } from './getters/getSelectedWeaponAttributeSet';
import { isRangedWeaponLoaded } from './getters/isRangedWeaponLoaded';
import { isWeildingShield } from './getters/isWeildingShield';
import { isWeildingTwoHandedWeapon } from './getters/isWeildingTwoHandedWeapon';

export function defineGetters(store: ReactiveStore<State>) {
    store.defineGetter('getDefensiveSlots', getDefensiveSlots);
    store.defineGetter('getEquipmentProperties', getEquipmentProperties);
    store.defineGetter('getEquipmentSlotProperties', getEquipmentSlotProperties);
    store.defineGetter('getInnateProperties', getInnateProperties);
    store.defineGetter('getOffensiveSlots', getOffensiveSlots);
    store.defineGetter('getSelectedWeaponAttributeSet', getSelectedWeaponAttributeSet);
    store.defineGetter('isRangedWeaponLoaded', isRangedWeaponLoaded);
    store.defineGetter('isWeildingShield', isWeildingShield);
    store.defineGetter('isWeildingTwoHandedWeapon', isWeildingTwoHandedWeapon);
}
