// File generated by build-getters-index

import { getAbilityBaseScores } from './getters/getAbilityBaseScores';
import { getAbilityModifiers } from './getters/getAbilityModifiers';
import { getAbilityScores } from './getters/getAbilityScores';
import { getDefensiveSlots } from './getters/getDefensiveSlots';
import { getEffects } from './getters/getEffects';
import { getEquipmentProperties } from './getters/getEquipmentProperties';
import { getEquipmentSlotProperties } from './getters/getEquipmentSlotProperties';
import { getInnateProperties } from './getters/getInnateProperties';
import { getOffensiveSlots } from './getters/getOffensiveSlots';
import { getSelectedWeaponAttributeSet } from './getters/getSelectedWeaponAttributeSet';
import { isActive } from './getters/isActive';
import { isRangedWeaponLoaded } from './getters/isRangedWeaponLoaded';
import { isWieldingShield } from './getters/isWieldingShield';
import { isWieldingTwoHandedWeapon } from './getters/isWieldingTwoHandedWeapon';

export type GetterReturnType = {
    getAbilityBaseScores: ReturnType<typeof getAbilityBaseScores>;
    getAbilityModifiers: ReturnType<typeof getAbilityModifiers>;
    getAbilityScores: ReturnType<typeof getAbilityScores>;
    getDefensiveSlots: ReturnType<typeof getDefensiveSlots>;
    getEffects: ReturnType<typeof getEffects>;
    getEquipmentProperties: ReturnType<typeof getEquipmentProperties>;
    getEquipmentSlotProperties: ReturnType<typeof getEquipmentSlotProperties>;
    getInnateProperties: ReturnType<typeof getInnateProperties>;
    getOffensiveSlots: ReturnType<typeof getOffensiveSlots>;
    getSelectedWeaponAttributeSet: ReturnType<typeof getSelectedWeaponAttributeSet>;
    isActive: ReturnType<typeof isActive>;
    isRangedWeaponLoaded: ReturnType<typeof isRangedWeaponLoaded>;
    isWieldingShield: ReturnType<typeof isWieldingShield>;
    isWieldingTwoHandedWeapon: ReturnType<typeof isWieldingTwoHandedWeapon>;
};

export const Getters = {
    getAbilityBaseScores,
    getAbilityModifiers,
    getAbilityScores,
    getDefensiveSlots,
    getEffects,
    getEquipmentProperties,
    getEquipmentSlotProperties,
    getInnateProperties,
    getOffensiveSlots,
    getSelectedWeaponAttributeSet,
    isActive,
    isRangedWeaponLoaded,
    isWieldingShield,
    isWieldingTwoHandedWeapon,
};
