// File generated by build-getters-index

import { getAbilityBaseScores } from './getters/getAbilityBaseScores';
import { getAbilityModifiers } from './getters/getAbilityModifiers';
import { getAbilityScores } from './getters/getAbilityScores';
import { getActions } from './getters/getActions';
import { getArmorClass } from './getters/getArmorClass';
import { getConditionSet } from './getters/getConditionSet';
import { getDefensiveSlots } from './getters/getDefensiveSlots';
import { getEffectSet } from './getters/getEffectSet';
import { getEffects } from './getters/getEffects';
import { getEquipmentProperties } from './getters/getEquipmentProperties';
import { getEquipmentSlotProperties } from './getters/getEquipmentSlotProperties';
import { getInnateProperties } from './getters/getInnateProperties';
import { getLevel } from './getters/getLevel';
import { getOffensiveSlots } from './getters/getOffensiveSlots';
import { getProficiencyBonus } from './getters/getProficiencyBonus';
import { getSavingThrowBonus } from './getters/getSavingThrowBonus';
import { getSelectedWeaponAttributeSet } from './getters/getSelectedWeaponAttributeSet';
import { getSpeed } from './getters/getSpeed';
import { isDead } from './getters/isDead';
import { isRangedWeaponLoaded } from './getters/isRangedWeaponLoaded';
import { isWieldingShield } from './getters/isWieldingShield';
import { isWieldingTwoHandedWeapon } from './getters/isWieldingTwoHandedWeapon';

export type GetterReturnType = {
    getAbilityBaseScores: ReturnType<typeof getAbilityBaseScores>;
    getAbilityModifiers: ReturnType<typeof getAbilityModifiers>;
    getAbilityScores: ReturnType<typeof getAbilityScores>;
    getActions: ReturnType<typeof getActions>;
    getArmorClass: ReturnType<typeof getArmorClass>;
    getConditionSet: ReturnType<typeof getConditionSet>;
    getDefensiveSlots: ReturnType<typeof getDefensiveSlots>;
    getEffectSet: ReturnType<typeof getEffectSet>;
    getEffects: ReturnType<typeof getEffects>;
    getEquipmentProperties: ReturnType<typeof getEquipmentProperties>;
    getEquipmentSlotProperties: ReturnType<typeof getEquipmentSlotProperties>;
    getInnateProperties: ReturnType<typeof getInnateProperties>;
    getLevel: ReturnType<typeof getLevel>;
    getOffensiveSlots: ReturnType<typeof getOffensiveSlots>;
    getProficiencyBonus: ReturnType<typeof getProficiencyBonus>;
    getSavingThrowBonus: ReturnType<typeof getSavingThrowBonus>;
    getSelectedWeaponAttributeSet: ReturnType<typeof getSelectedWeaponAttributeSet>;
    getSpeed: ReturnType<typeof getSpeed>;
    isDead: ReturnType<typeof isDead>;
    isRangedWeaponLoaded: ReturnType<typeof isRangedWeaponLoaded>;
    isWieldingShield: ReturnType<typeof isWieldingShield>;
    isWieldingTwoHandedWeapon: ReturnType<typeof isWieldingTwoHandedWeapon>;
};

export const Getters = {
    getAbilityBaseScores,
    getAbilityModifiers,
    getAbilityScores,
    getActions,
    getArmorClass,
    getConditionSet,
    getDefensiveSlots,
    getEffectSet,
    getEffects,
    getEquipmentProperties,
    getEquipmentSlotProperties,
    getInnateProperties,
    getLevel,
    getOffensiveSlots,
    getProficiencyBonus,
    getSavingThrowBonus,
    getSelectedWeaponAttributeSet,
    getSpeed,
    isDead,
    isRangedWeaponLoaded,
    isWieldingShield,
    isWieldingTwoHandedWeapon,
};
