// generated by build-module-index classic

import cp_construct_armored from './blueprints/creatures/common-props/cp-construct-armored.json';
import cp_unholy from './blueprints/creatures/common-props/cp-unholy.json';
import cp_lifeless from './blueprints/creatures/common-props/cp-lifeless.json';
import cp_construct_mineral from './blueprints/creatures/common-props/cp-construct-mineral.json';
import cp_undead_skeleton from './blueprints/creatures/common-props/cp-undead-skeleton.json';
import cp_construct_metal from './blueprints/creatures/common-props/cp-construct-metal.json';
import cp_flawed_deflective_skin from './blueprints/creatures/common-props/cp-flawed-deflective-skin.json';
import cp_deflective_skin from './blueprints/creatures/common-props/cp-deflective-skin.json';
import cp_mindless from './blueprints/creatures/common-props/cp-mindless.json';
import cp_hard_skin from './blueprints/creatures/common-props/cp-hard-skin.json';
import cp_freedom from './blueprints/creatures/common-props/cp-freedom.json';
import cp_fiend from './blueprints/creatures/common-props/cp-fiend.json';
import cp_undead from './blueprints/creatures/common-props/cp-undead.json';
import cp_celestial from './blueprints/creatures/common-props/cp-celestial.json';
import cp_ultra_deflective_skin from './blueprints/creatures/common-props/cp-ultra-deflective-skin.json';
import cp_poison_immunity from './blueprints/creatures/common-props/cp-poison-immunity.json';
import cp_construct_organic from './blueprints/creatures/common-props/cp-construct-organic.json';
import cp_construct from './blueprints/creatures/common-props/cp-construct.json';
import cp_undead_ethereal from './blueprints/creatures/common-props/cp-undead-ethereal.json';
import cp_undead_corporeal from './blueprints/creatures/common-props/cp-undead-corporeal.json';
import c_goblin from './blueprints/creatures/monsters/c-goblin.json';
import c_skeleton from './blueprints/creatures/monsters/c-skeleton.json';
import c_harpy from './blueprints/creatures/monsters/c-harpy.json';
import c_zombie from './blueprints/creatures/monsters/c-zombie.json';
import c_ghost from './blueprints/creatures/monsters/c-ghost.json';
import c_golem_iron from './blueprints/creatures/monsters/c-golem-iron.json';
import c_dragon_red_ancient from './blueprints/creatures/monsters/c-dragon-red-ancient.json';
import c_golem_flesh from './blueprints/creatures/monsters/c-golem-flesh.json';
import c_basilisk from './blueprints/creatures/monsters/c-basilisk.json';
import c_vampire from './blueprints/creatures/monsters/c-vampire.json';
import c_ogre from './blueprints/creatures/monsters/c-ogre.json';
import c_gorgon from './blueprints/creatures/monsters/c-gorgon.json';
import c_golem_clay from './blueprints/creatures/monsters/c-golem-clay.json';
import c_dragon_red from './blueprints/creatures/monsters/c-dragon-red.json';
import c_minotaur from './blueprints/creatures/monsters/c-minotaur.json';
import c_wyvern from './blueprints/creatures/monsters/c-wyvern.json';
import c_basilisk_greater from './blueprints/creatures/monsters/c-basilisk-greater.json';
import c_goblin_warrior from './blueprints/creatures/monsters/c-goblin-warrior.json';
import c_cockatrice from './blueprints/creatures/monsters/c-cockatrice.json';
import c_gargoyle from './blueprints/creatures/monsters/c-gargoyle.json';
import c_hippogriff from './blueprints/creatures/monsters/c-hippogriff.json';
import c_mummy from './blueprints/creatures/monsters/c-mummy.json';
import c_wight from './blueprints/creatures/monsters/c-wight.json';
import c_griffon from './blueprints/creatures/monsters/c-griffon.json';
import c_golem_bronze from './blueprints/creatures/monsters/c-golem-bronze.json';
import c_succubus from './blueprints/creatures/monsters/c-succubus.json';
import c_hydra from './blueprints/creatures/monsters/c-hydra.json';
import c_rat_giant from './blueprints/creatures/monsters/c-rat-giant.json';
import c_ghoul from './blueprints/creatures/monsters/c-ghoul.json';
import c_orc from './blueprints/creatures/monsters/c-orc.json';
import c_centaur from './blueprints/creatures/monsters/c-centaur.json';
import c_ghast from './blueprints/creatures/monsters/c-ghast.json';
import c_medusa from './blueprints/creatures/monsters/c-medusa.json';
import c_golem_stone from './blueprints/creatures/monsters/c-golem-stone.json';
import c_manticore from './blueprints/creatures/monsters/c-manticore.json';
import c_troll from './blueprints/creatures/monsters/c-troll.json';
import c_skeleton_warrior from './blueprints/creatures/monsters/c-skeleton-warrior.json';
import c_chimera from './blueprints/creatures/monsters/c-chimera.json';
import c_deva from './blueprints/creatures/monsters/c-deva.json';
import shd_medium from './blueprints/items/shields/shd-medium.json';
import shd_small from './blueprints/items/shields/shd-small.json';
import shd_large from './blueprints/items/shields/shd-large.json';
import arm_chain_shirt_p2 from './blueprints/items/armors/arm-chain-shirt-p2.json';
import arm_ring_mail_p1 from './blueprints/items/armors/arm-ring-mail-p1.json';
import arm_hide_p1 from './blueprints/items/armors/arm-hide-p1.json';
import arm_scale_mail_p2 from './blueprints/items/armors/arm-scale-mail-p2.json';
import arm_breast_plate from './blueprints/items/armors/arm-breast-plate.json';
import arm_half_plate from './blueprints/items/armors/arm-half-plate.json';
import arm_leather_p2 from './blueprints/items/armors/arm-leather-p2.json';
import arm_studded_leather from './blueprints/items/armors/arm-studded-leather.json';
import arm_chain_mail from './blueprints/items/armors/arm-chain-mail.json';
import arm_scale_mail from './blueprints/items/armors/arm-scale-mail.json';
import arm_hide from './blueprints/items/armors/arm-hide.json';
import arm_leather from './blueprints/items/armors/arm-leather.json';
import arm_chain_mail_p1 from './blueprints/items/armors/arm-chain-mail-p1.json';
import arm_plate_p2 from './blueprints/items/armors/arm-plate-p2.json';
import arm_plate_p1 from './blueprints/items/armors/arm-plate-p1.json';
import arm_chain_mail_p2 from './blueprints/items/armors/arm-chain-mail-p2.json';
import arm_ring_mail_p2 from './blueprints/items/armors/arm-ring-mail-p2.json';
import arm_breast_plate_p2 from './blueprints/items/armors/arm-breast-plate-p2.json';
import arm_splint_p2 from './blueprints/items/armors/arm-splint-p2.json';
import arm_chain_shirt from './blueprints/items/armors/arm-chain-shirt.json';
import arm_hide_p2 from './blueprints/items/armors/arm-hide-p2.json';
import arm_splint_p1 from './blueprints/items/armors/arm-splint-p1.json';
import arm_studded_leather_p2 from './blueprints/items/armors/arm-studded-leather-p2.json';
import arm_ring_mail from './blueprints/items/armors/arm-ring-mail.json';
import arm_scale_mail_p1 from './blueprints/items/armors/arm-scale-mail-p1.json';
import arm_studded_leather_p1 from './blueprints/items/armors/arm-studded-leather-p1.json';
import arm_chain_shirt_p1 from './blueprints/items/armors/arm-chain-shirt-p1.json';
import arm_half_plate_p1 from './blueprints/items/armors/arm-half-plate-p1.json';
import arm_half_plate_p2 from './blueprints/items/armors/arm-half-plate-p2.json';
import arm_plate from './blueprints/items/armors/arm-plate.json';
import arm_leather_p1 from './blueprints/items/armors/arm-leather-p1.json';
import arm_splint from './blueprints/items/armors/arm-splint.json';
import arm_breast_plate_p1 from './blueprints/items/armors/arm-breast-plate-p1.json';
import gear_gloves from './blueprints/items/gear/gear-gloves.json';
import gear_hat from './blueprints/items/gear/gear-hat.json';
import gear_helm from './blueprints/items/gear/gear-helm.json';
import gear_gauntlets from './blueprints/items/gear/gear-gauntlets.json';
import gear_ring from './blueprints/items/gear/gear-ring.json';
import gear_belt from './blueprints/items/gear/gear-belt.json';
import gear_bracers from './blueprints/items/gear/gear-bracers.json';
import gear_boots from './blueprints/items/gear/gear-boots.json';
import gear_necklace from './blueprints/items/gear/gear-necklace.json';
import gear_torch from './blueprints/items/gear/gear-torch.json';
import ammo_quarrel_hq from './blueprints/items/ammo/ammo-quarrel-hq.json';
import ammo_quarrel_p1 from './blueprints/items/ammo/ammo-quarrel-p1.json';
import ammo_quarrel_p2 from './blueprints/items/ammo/ammo-quarrel-p2.json';
import ammo_arrow from './blueprints/items/ammo/ammo-arrow.json';
import ammo_quarrel from './blueprints/items/ammo/ammo-quarrel.json';
import ammo_arrow_p2 from './blueprints/items/ammo/ammo-arrow-p2.json';
import ammo_arrow_hq from './blueprints/items/ammo/ammo-arrow-hq.json';
import ammo_arrow_fire from './blueprints/items/ammo/ammo-arrow-fire.json';
import ammo_arrow_p1 from './blueprints/items/ammo/ammo-arrow-p1.json';
import ammo_quarrel_fire from './blueprints/items/ammo/ammo-quarrel-fire.json';
import wpn_dagger_hq from './blueprints/items/weapons/wpn-dagger-hq.json';
import wpn_light_crossbow_p1 from './blueprints/items/weapons/wpn-light-crossbow-p1.json';
import wpn_heavy_crossbow from './blueprints/items/weapons/wpn-heavy-crossbow.json';
import wpn_mace from './blueprints/items/weapons/wpn-mace.json';
import wpn_light_crossbow_p2 from './blueprints/items/weapons/wpn-light-crossbow-p2.json';
import wpn_short_sword_hq from './blueprints/items/weapons/wpn-short-sword-hq.json';
import wpn_long_sword_wight from './blueprints/items/weapons/wpn-long-sword-wight.json';
import wpn_long_bow_p1 from './blueprints/items/weapons/wpn-long-bow-p1.json';
import wpn_battle_axe_p1 from './blueprints/items/weapons/wpn-battle-axe-p1.json';
import wpn_halberd_p1 from './blueprints/items/weapons/wpn-halberd-p1.json';
import wpn_quarterstaff_hq from './blueprints/items/weapons/wpn-quarterstaff-hq.json';
import wpn_morgenstern_p1 from './blueprints/items/weapons/wpn-morgenstern-p1.json';
import wpn_mace_hq from './blueprints/items/weapons/wpn-mace-hq.json';
import wpn_great_axe from './blueprints/items/weapons/wpn-great-axe.json';
import wpn_long_sword_p1 from './blueprints/items/weapons/wpn-long-sword-p1.json';
import wpn_long_sword_hq from './blueprints/items/weapons/wpn-long-sword-hq.json';
import wpn_long_sword_p2 from './blueprints/items/weapons/wpn-long-sword-p2.json';
import wpn_short_bow_p2 from './blueprints/items/weapons/wpn-short-bow-p2.json';
import wpn_heavy_crossbow_p1 from './blueprints/items/weapons/wpn-heavy-crossbow-p1.json';
import wpn_heavy_crossbow_p2 from './blueprints/items/weapons/wpn-heavy-crossbow-p2.json';
import wpn_short_bow_p1 from './blueprints/items/weapons/wpn-short-bow-p1.json';
import wpn_mace_deva from './blueprints/items/weapons/wpn-mace-deva.json';
import wpn_halberd from './blueprints/items/weapons/wpn-halberd.json';
import wpn_quarterstaff from './blueprints/items/weapons/wpn-quarterstaff.json';
import wpn_light_crossbow from './blueprints/items/weapons/wpn-light-crossbow.json';
import wpn_morgenstern from './blueprints/items/weapons/wpn-morgenstern.json';
import wpn_short_bow from './blueprints/items/weapons/wpn-short-bow.json';
import wpn_short_spear_hq from './blueprints/items/weapons/wpn-short-spear-hq.json';
import wpn_morgenstern_p2 from './blueprints/items/weapons/wpn-morgenstern-p2.json';
import wpn_halberd_hq from './blueprints/items/weapons/wpn-halberd-hq.json';
import wpn_long_bow_p2 from './blueprints/items/weapons/wpn-long-bow-p2.json';
import wpn_long_bow_hq from './blueprints/items/weapons/wpn-long-bow-hq.json';
import wpn_dagger_p2 from './blueprints/items/weapons/wpn-dagger-p2.json';
import wpn_quarterstaff_p2 from './blueprints/items/weapons/wpn-quarterstaff-p2.json';
import wpn_long_sword from './blueprints/items/weapons/wpn-long-sword.json';
import wpn_short_spear from './blueprints/items/weapons/wpn-short-spear.json';
import wpn_great_axe_p1 from './blueprints/items/weapons/wpn-great-axe-p1.json';
import wpn_dagger from './blueprints/items/weapons/wpn-dagger.json';
import wpn_short_sword_p2 from './blueprints/items/weapons/wpn-short-sword-p2.json';
import wpn_short_sword from './blueprints/items/weapons/wpn-short-sword.json';
import wpn_dagger_p1 from './blueprints/items/weapons/wpn-dagger-p1.json';
import wpn_battle_axe_hq from './blueprints/items/weapons/wpn-battle-axe-hq.json';
import wpn_short_spear_p1 from './blueprints/items/weapons/wpn-short-spear-p1.json';
import wpn_great_axe_hq from './blueprints/items/weapons/wpn-great-axe-hq.json';
import wpn_morgenstern_hq from './blueprints/items/weapons/wpn-morgenstern-hq.json';
import wpn_mace_p1 from './blueprints/items/weapons/wpn-mace-p1.json';
import wpn_mace_p2 from './blueprints/items/weapons/wpn-mace-p2.json';
import wpn_halberd_p2 from './blueprints/items/weapons/wpn-halberd-p2.json';
import wpn_long_bow from './blueprints/items/weapons/wpn-long-bow.json';
import wpn_battle_axe from './blueprints/items/weapons/wpn-battle-axe.json';
import wpn_quarterstaff_p1 from './blueprints/items/weapons/wpn-quarterstaff-p1.json';
import wpn_great_axe_p2 from './blueprints/items/weapons/wpn-great-axe-p2.json';
import wpn_battle_axe_p2 from './blueprints/items/weapons/wpn-battle-axe-p2.json';
import wpn_light_crossbow_hq from './blueprints/items/weapons/wpn-light-crossbow-hq.json';
import wpn_short_sword_p1 from './blueprints/items/weapons/wpn-short-sword-p1.json';
import wpn_short_bow_hq from './blueprints/items/weapons/wpn-short-bow-hq.json';
import wpn_short_spear_p2 from './blueprints/items/weapons/wpn-short-spear-p2.json';
import wpn_heavy_crossbow_hq from './blueprints/items/weapons/wpn-heavy-crossbow-hq.json';
import ammo_type_quarrel from './blueprints/types/ammo-types/ammo-type-quarrel.json';
import ammo_type_arrow from './blueprints/types/ammo-types/ammo-type-arrow.json';
import shd_type_medium from './blueprints/types/shield-types/shd-type-medium.json';
import shd_type_large from './blueprints/types/shield-types/shd-type-large.json';
import shd_type_small from './blueprints/types/shield-types/shd-type-small.json';
import wpn_type_halberd from './blueprints/types/weapon-types/wpn-type-halberd.json';
import wpn_type_quarterstaff from './blueprints/types/weapon-types/wpn-type-quarterstaff.json';
import wpn_type_battle_axe from './blueprints/types/weapon-types/wpn-type-battle-axe.json';
import wpn_type_heavy_crossbow from './blueprints/types/weapon-types/wpn-type-heavy-crossbow.json';
import wpn_type_short_bow from './blueprints/types/weapon-types/wpn-type-short-bow.json';
import wpn_type_long_sword from './blueprints/types/weapon-types/wpn-type-long-sword.json';
import wpn_type_great_axe from './blueprints/types/weapon-types/wpn-type-great-axe.json';
import wpn_type_light_crossbow from './blueprints/types/weapon-types/wpn-type-light-crossbow.json';
import wpn_type_short_sword from './blueprints/types/weapon-types/wpn-type-short-sword.json';
import wpn_type_short_spear from './blueprints/types/weapon-types/wpn-type-short-spear.json';
import wpn_type_morgenstern from './blueprints/types/weapon-types/wpn-type-morgenstern.json';
import wpn_type_long_bow from './blueprints/types/weapon-types/wpn-type-long-bow.json';
import wpn_type_dagger from './blueprints/types/weapon-types/wpn-type-dagger.json';
import wpn_type_mace from './blueprints/types/weapon-types/wpn-type-mace.json';
import gear_type_necklace from './blueprints/types/gear-types/gear-type-necklace.json';
import gear_type_boots from './blueprints/types/gear-types/gear-type-boots.json';
import gear_type_gauntlets from './blueprints/types/gear-types/gear-type-gauntlets.json';
import gear_type_hat from './blueprints/types/gear-types/gear-type-hat.json';
import gear_type_bracers from './blueprints/types/gear-types/gear-type-bracers.json';
import gear_type_torch from './blueprints/types/gear-types/gear-type-torch.json';
import gear_type_belt from './blueprints/types/gear-types/gear-type-belt.json';
import gear_type_helm from './blueprints/types/gear-types/gear-type-helm.json';
import gear_type_gloves from './blueprints/types/gear-types/gear-type-gloves.json';
import gear_type_ring from './blueprints/types/gear-types/gear-type-ring.json';
import arm_type_splint from './blueprints/types/armor-types/arm-type-splint.json';
import arm_type_ring_mail from './blueprints/types/armor-types/arm-type-ring-mail.json';
import arm_type_chain_shirt from './blueprints/types/armor-types/arm-type-chain-shirt.json';
import arm_type_leather from './blueprints/types/armor-types/arm-type-leather.json';
import arm_type_breast_plate from './blueprints/types/armor-types/arm-type-breast-plate.json';
import arm_type_studded_leather from './blueprints/types/armor-types/arm-type-studded-leather.json';
import arm_type_scale_mail from './blueprints/types/armor-types/arm-type-scale-mail.json';
import arm_type_hide from './blueprints/types/armor-types/arm-type-hide.json';
import arm_type_chain_mail from './blueprints/types/armor-types/arm-type-chain-mail.json';
import arm_type_half_plate from './blueprints/types/armor-types/arm-type-half-plate.json';
import arm_type_plate from './blueprints/types/armor-types/arm-type-plate.json';

export default {
    blueprints: {
        'cp-construct-armored': cp_construct_armored,
        'cp-unholy': cp_unholy,
        'cp-lifeless': cp_lifeless,
        'cp-construct-mineral': cp_construct_mineral,
        'cp-undead-skeleton': cp_undead_skeleton,
        'cp-construct-metal': cp_construct_metal,
        'cp-flawed-deflective-skin': cp_flawed_deflective_skin,
        'cp-deflective-skin': cp_deflective_skin,
        'cp-mindless': cp_mindless,
        'cp-hard-skin': cp_hard_skin,
        'cp-freedom': cp_freedom,
        'cp-fiend': cp_fiend,
        'cp-undead': cp_undead,
        'cp-celestial': cp_celestial,
        'cp-ultra-deflective-skin': cp_ultra_deflective_skin,
        'cp-poison-immunity': cp_poison_immunity,
        'cp-construct-organic': cp_construct_organic,
        'cp-construct': cp_construct,
        'cp-undead-ethereal': cp_undead_ethereal,
        'cp-undead-corporeal': cp_undead_corporeal,
        'c-goblin': c_goblin,
        'c-skeleton': c_skeleton,
        'c-harpy': c_harpy,
        'c-zombie': c_zombie,
        'c-ghost': c_ghost,
        'c-golem-iron': c_golem_iron,
        'c-dragon-red-ancient': c_dragon_red_ancient,
        'c-golem-flesh': c_golem_flesh,
        'c-basilisk': c_basilisk,
        'c-vampire': c_vampire,
        'c-ogre': c_ogre,
        'c-gorgon': c_gorgon,
        'c-golem-clay': c_golem_clay,
        'c-dragon-red': c_dragon_red,
        'c-minotaur': c_minotaur,
        'c-wyvern': c_wyvern,
        'c-basilisk-greater': c_basilisk_greater,
        'c-goblin-warrior': c_goblin_warrior,
        'c-cockatrice': c_cockatrice,
        'c-gargoyle': c_gargoyle,
        'c-hippogriff': c_hippogriff,
        'c-mummy': c_mummy,
        'c-wight': c_wight,
        'c-griffon': c_griffon,
        'c-golem-bronze': c_golem_bronze,
        'c-succubus': c_succubus,
        'c-hydra': c_hydra,
        'c-rat-giant': c_rat_giant,
        'c-ghoul': c_ghoul,
        'c-orc': c_orc,
        'c-centaur': c_centaur,
        'c-ghast': c_ghast,
        'c-medusa': c_medusa,
        'c-golem-stone': c_golem_stone,
        'c-manticore': c_manticore,
        'c-troll': c_troll,
        'c-skeleton-warrior': c_skeleton_warrior,
        'c-chimera': c_chimera,
        'c-deva': c_deva,
        'shd-medium': shd_medium,
        'shd-small': shd_small,
        'shd-large': shd_large,
        'arm-chain-shirt-p2': arm_chain_shirt_p2,
        'arm-ring-mail-p1': arm_ring_mail_p1,
        'arm-hide-p1': arm_hide_p1,
        'arm-scale-mail-p2': arm_scale_mail_p2,
        'arm-breast-plate': arm_breast_plate,
        'arm-half-plate': arm_half_plate,
        'arm-leather-p2': arm_leather_p2,
        'arm-studded-leather': arm_studded_leather,
        'arm-chain-mail': arm_chain_mail,
        'arm-scale-mail': arm_scale_mail,
        'arm-hide': arm_hide,
        'arm-leather': arm_leather,
        'arm-chain-mail-p1': arm_chain_mail_p1,
        'arm-plate-p2': arm_plate_p2,
        'arm-plate-p1': arm_plate_p1,
        'arm-chain-mail-p2': arm_chain_mail_p2,
        'arm-ring-mail-p2': arm_ring_mail_p2,
        'arm-breast-plate-p2': arm_breast_plate_p2,
        'arm-splint-p2': arm_splint_p2,
        'arm-chain-shirt': arm_chain_shirt,
        'arm-hide-p2': arm_hide_p2,
        'arm-splint-p1': arm_splint_p1,
        'arm-studded-leather-p2': arm_studded_leather_p2,
        'arm-ring-mail': arm_ring_mail,
        'arm-scale-mail-p1': arm_scale_mail_p1,
        'arm-studded-leather-p1': arm_studded_leather_p1,
        'arm-chain-shirt-p1': arm_chain_shirt_p1,
        'arm-half-plate-p1': arm_half_plate_p1,
        'arm-half-plate-p2': arm_half_plate_p2,
        'arm-plate': arm_plate,
        'arm-leather-p1': arm_leather_p1,
        'arm-splint': arm_splint,
        'arm-breast-plate-p1': arm_breast_plate_p1,
        'gear-gloves': gear_gloves,
        'gear-hat': gear_hat,
        'gear-helm': gear_helm,
        'gear-gauntlets': gear_gauntlets,
        'gear-ring': gear_ring,
        'gear-belt': gear_belt,
        'gear-bracers': gear_bracers,
        'gear-boots': gear_boots,
        'gear-necklace': gear_necklace,
        'gear-torch': gear_torch,
        'ammo-quarrel-hq': ammo_quarrel_hq,
        'ammo-quarrel-p1': ammo_quarrel_p1,
        'ammo-quarrel-p2': ammo_quarrel_p2,
        'ammo-arrow': ammo_arrow,
        'ammo-quarrel': ammo_quarrel,
        'ammo-arrow-p2': ammo_arrow_p2,
        'ammo-arrow-hq': ammo_arrow_hq,
        'ammo-arrow-fire': ammo_arrow_fire,
        'ammo-arrow-p1': ammo_arrow_p1,
        'ammo-quarrel-fire': ammo_quarrel_fire,
        'wpn-dagger-hq': wpn_dagger_hq,
        'wpn-light-crossbow-p1': wpn_light_crossbow_p1,
        'wpn-heavy-crossbow': wpn_heavy_crossbow,
        'wpn-mace': wpn_mace,
        'wpn-light-crossbow-p2': wpn_light_crossbow_p2,
        'wpn-short-sword-hq': wpn_short_sword_hq,
        'wpn-long-sword-wight': wpn_long_sword_wight,
        'wpn-long-bow-p1': wpn_long_bow_p1,
        'wpn-battle-axe-p1': wpn_battle_axe_p1,
        'wpn-halberd-p1': wpn_halberd_p1,
        'wpn-quarterstaff-hq': wpn_quarterstaff_hq,
        'wpn-morgenstern-p1': wpn_morgenstern_p1,
        'wpn-mace-hq': wpn_mace_hq,
        'wpn-great-axe': wpn_great_axe,
        'wpn-long-sword-p1': wpn_long_sword_p1,
        'wpn-long-sword-hq': wpn_long_sword_hq,
        'wpn-long-sword-p2': wpn_long_sword_p2,
        'wpn-short-bow-p2': wpn_short_bow_p2,
        'wpn-heavy-crossbow-p1': wpn_heavy_crossbow_p1,
        'wpn-heavy-crossbow-p2': wpn_heavy_crossbow_p2,
        'wpn-short-bow-p1': wpn_short_bow_p1,
        'wpn-mace-deva': wpn_mace_deva,
        'wpn-halberd': wpn_halberd,
        'wpn-quarterstaff': wpn_quarterstaff,
        'wpn-light-crossbow': wpn_light_crossbow,
        'wpn-morgenstern': wpn_morgenstern,
        'wpn-short-bow': wpn_short_bow,
        'wpn-short-spear-hq': wpn_short_spear_hq,
        'wpn-morgenstern-p2': wpn_morgenstern_p2,
        'wpn-halberd-hq': wpn_halberd_hq,
        'wpn-long-bow-p2': wpn_long_bow_p2,
        'wpn-long-bow-hq': wpn_long_bow_hq,
        'wpn-dagger-p2': wpn_dagger_p2,
        'wpn-quarterstaff-p2': wpn_quarterstaff_p2,
        'wpn-long-sword': wpn_long_sword,
        'wpn-short-spear': wpn_short_spear,
        'wpn-great-axe-p1': wpn_great_axe_p1,
        'wpn-dagger': wpn_dagger,
        'wpn-short-sword-p2': wpn_short_sword_p2,
        'wpn-short-sword': wpn_short_sword,
        'wpn-dagger-p1': wpn_dagger_p1,
        'wpn-battle-axe-hq': wpn_battle_axe_hq,
        'wpn-short-spear-p1': wpn_short_spear_p1,
        'wpn-great-axe-hq': wpn_great_axe_hq,
        'wpn-morgenstern-hq': wpn_morgenstern_hq,
        'wpn-mace-p1': wpn_mace_p1,
        'wpn-mace-p2': wpn_mace_p2,
        'wpn-halberd-p2': wpn_halberd_p2,
        'wpn-long-bow': wpn_long_bow,
        'wpn-battle-axe': wpn_battle_axe,
        'wpn-quarterstaff-p1': wpn_quarterstaff_p1,
        'wpn-great-axe-p2': wpn_great_axe_p2,
        'wpn-battle-axe-p2': wpn_battle_axe_p2,
        'wpn-light-crossbow-hq': wpn_light_crossbow_hq,
        'wpn-short-sword-p1': wpn_short_sword_p1,
        'wpn-short-bow-hq': wpn_short_bow_hq,
        'wpn-short-spear-p2': wpn_short_spear_p2,
        'wpn-heavy-crossbow-hq': wpn_heavy_crossbow_hq,
        'ammo-type-quarrel': ammo_type_quarrel,
        'ammo-type-arrow': ammo_type_arrow,
        'shd-type-medium': shd_type_medium,
        'shd-type-large': shd_type_large,
        'shd-type-small': shd_type_small,
        'wpn-type-halberd': wpn_type_halberd,
        'wpn-type-quarterstaff': wpn_type_quarterstaff,
        'wpn-type-battle-axe': wpn_type_battle_axe,
        'wpn-type-heavy-crossbow': wpn_type_heavy_crossbow,
        'wpn-type-short-bow': wpn_type_short_bow,
        'wpn-type-long-sword': wpn_type_long_sword,
        'wpn-type-great-axe': wpn_type_great_axe,
        'wpn-type-light-crossbow': wpn_type_light_crossbow,
        'wpn-type-short-sword': wpn_type_short_sword,
        'wpn-type-short-spear': wpn_type_short_spear,
        'wpn-type-morgenstern': wpn_type_morgenstern,
        'wpn-type-long-bow': wpn_type_long_bow,
        'wpn-type-dagger': wpn_type_dagger,
        'wpn-type-mace': wpn_type_mace,
        'gear-type-necklace': gear_type_necklace,
        'gear-type-boots': gear_type_boots,
        'gear-type-gauntlets': gear_type_gauntlets,
        'gear-type-hat': gear_type_hat,
        'gear-type-bracers': gear_type_bracers,
        'gear-type-torch': gear_type_torch,
        'gear-type-belt': gear_type_belt,
        'gear-type-helm': gear_type_helm,
        'gear-type-gloves': gear_type_gloves,
        'gear-type-ring': gear_type_ring,
        'arm-type-splint': arm_type_splint,
        'arm-type-ring-mail': arm_type_ring_mail,
        'arm-type-chain-shirt': arm_type_chain_shirt,
        'arm-type-leather': arm_type_leather,
        'arm-type-breast-plate': arm_type_breast_plate,
        'arm-type-studded-leather': arm_type_studded_leather,
        'arm-type-scale-mail': arm_type_scale_mail,
        'arm-type-hide': arm_type_hide,
        'arm-type-chain-mail': arm_type_chain_mail,
        'arm-type-half-plate': arm_type_half_plate,
        'arm-type-plate': arm_type_plate,
    },
};
