// generated by build-module-index classic

import c_golem_bronze from './blueprints/creatures/c-golem-bronze.json';
import cp_lifeless from './blueprints/partials/creatures/cp-lifeless.json';
import cp_construct_metal from './blueprints/partials/creatures/cp-construct-metal.json';
import cp_deflective_skin from './blueprints/partials/creatures/cp-deflective-skin.json';
import cp_mindless from './blueprints/partials/creatures/cp-mindless.json';
import cp_poison_immunity from './blueprints/partials/creatures/cp-poison-immunity.json';
import cp_construct from './blueprints/partials/creatures/cp-construct.json';

export default {
    blueprints: {
        'c-golem-bronze': c_golem_bronze,
        'cp-lifeless': cp_lifeless,
        'cp-construct-metal': cp_construct_metal,
        'cp-deflective-skin': cp_deflective_skin,
        'cp-mindless': cp_mindless,
        'cp-poison-immunity': cp_poison_immunity,
        'cp-construct': cp_construct,
    },
};
