// File generated by build-properties-index
import z from 'zod';
import { PropertyAbilityCheckModifier } from './ability-check-modifier';
import { PropertyAbilityModifier } from './ability-modifier';
import { PropertyAdvantageAttack } from './advantage-attack';
import { PropertyAdvantageSavingThrow } from './advantage-saving-throw';
import { PropertyArmorClassModifier } from './armor-class-modifier';
import { PropertyAttackCountModifier } from './attack-count-modifier';
import { PropertyAttackModifier } from './attack-modifier';
import { PropertyCriticalRangeModifier } from './critical-range-modifier';
import { PropertyCursed } from './cursed';
import { PropertyDamageImmunity } from './damage-immunity';
import { PropertyDamageModifier } from './damage-modifier';
import { PropertyDamageReduction } from './damage-reduction';
import { PropertyDamageResistance } from './damage-resistance';
import { PropertyDamageVulnerability } from './damage-vulnerability';
import { PropertyDarkvision } from './darkvision';
import { PropertyDisadvantageAttack } from './disadvantage-attack';
import { PropertyDisadvantageSavingThrow } from './disadvantage-saving-throw';
import { PropertyEnfeeblement } from './enfeeblement';
import { PropertyExtraHitpoints } from './extra-hitpoints';
import { PropertyExtraWeaponDamageType } from './extra-weapon-damage-type';
import { PropertyWeightFactor } from './extra-weight';
import { PropertyFeat } from './feat';
import { PropertyHealingFactor } from './healing-factor';
import { PropertyHealingModifier } from './healing-modifier';
import { PropertyImmunity } from './immunity';
import { PropertyLight } from './light';
import { PropertyMaxDexterityBonus } from './max-dexterity-bonus';
import { PropertyOnAttackHit } from './on-attack-hit';
import { PropertyRegeneration } from './regeneration';
import { PropertySavingThrowModifier } from './saving-throw-modifier';
import { PropertySkillModifier } from './skill-modifier';
import { PropertySneakAttack } from './sneak-attack';
import { PropertySpeedFactor } from './speed-factor';
import { PropertySpellPower } from './spell-power';
import { PropertySpikeDamage } from './spike-damage';
import { PropertyThinker } from './thinker';
import { PropertyUnidentified } from './unidentified';
import { PropertyVampyre } from './vampyre';
import { PropertyWeaponDamageModifier } from './weapon-damage-modifier';

export const PropertySchema = z.discriminatedUnion('type', [
    PropertyAbilityCheckModifier,
    PropertyAbilityModifier,
    PropertyAdvantageAttack,
    PropertyAdvantageSavingThrow,
    PropertyArmorClassModifier,
    PropertyAttackCountModifier,
    PropertyAttackModifier,
    PropertyCriticalRangeModifier,
    PropertyCursed,
    PropertyDamageImmunity,
    PropertyDamageModifier,
    PropertyDamageReduction,
    PropertyDamageResistance,
    PropertyDamageVulnerability,
    PropertyDarkvision,
    PropertyDisadvantageAttack,
    PropertyDisadvantageSavingThrow,
    PropertyEnfeeblement,
    PropertyExtraHitpoints,
    PropertyExtraWeaponDamageType,
    PropertyWeightFactor,
    PropertyFeat,
    PropertyHealingFactor,
    PropertyHealingModifier,
    PropertyImmunity,
    PropertyLight,
    PropertyMaxDexterityBonus,
    PropertyOnAttackHit,
    PropertyRegeneration,
    PropertySavingThrowModifier,
    PropertySkillModifier,
    PropertySneakAttack,
    PropertySpeedFactor,
    PropertySpellPower,
    PropertySpikeDamage,
    PropertyThinker,
    PropertyUnidentified,
    PropertyVampyre,
    PropertyWeaponDamageModifier,
]);

export type Property = z.infer<typeof PropertySchema>;
