// File generated by build-properties-index
import z from 'zod';
import { PropertyDefinitionAbilityCheckModifier } from './ability-check-modifier';
import { PropertyDefinitionAbilityModifier } from './ability-modifier';
import { PropertyDefinitionAdvantageAttack } from './advantage-attack';
import { PropertyDefinitionAdvantageSavingThrow } from './advantage-saving-throw';
import { PropertyDefinitionAilment } from './ailment';
import { PropertyDefinitionArmorClassModifier } from './armor-class-modifier';
import { PropertyDefinitionAttackCountModifier } from './attack-count-modifier';
import { PropertyDefinitionAttackModifier } from './attack-modifier';
import { PropertyDefinitionCriticalRangeModifier } from './critical-range-modifier';
import { PropertyDefinitionCursed } from './cursed';
import { PropertyDefinitionDamageImmunity } from './damage-immunity';
import { PropertyDefinitionDamageModifier } from './damage-modifier';
import { PropertyDefinitionDamageReduction } from './damage-reduction';
import { PropertyDefinitionDamageResistance } from './damage-resistance';
import { PropertyDefinitionDamageVulnerability } from './damage-vulnerability';
import { PropertyDefinitionDarkvision } from './darkvision';
import { PropertyDefinitionDisadvantageAttack } from './disadvantage-attack';
import { PropertyDefinitionDisadvantageSavingThrow } from './disadvantage-saving-throw';
import { PropertyDefinitionEnfeeblement } from './enfeeblement';
import { PropertyDefinitionExtraHitpoints } from './extra-hitpoints';
import { PropertyDefinitionExtraWeaponDamageType } from './extra-weapon-damage-type';
import { PropertyDefinitionWeightFactor } from './extra-weight';
import { PropertyDefinitionFeat } from './feat';
import { PropertyDefinitionHealingFactor } from './healing-factor';
import { PropertyDefinitionHealingModifier } from './healing-modifier';
import { PropertyDefinitionImmunity } from './immunity';
import { PropertyDefinitionLight } from './light';
import { PropertyDefinitionMaxDexterityBonus } from './max-dexterity-bonus';
import { PropertyDefinitionProtectionFromSpecie } from './protection-from-specie';
import { PropertyDefinitionRegeneration } from './regeneration';
import { PropertyDefinitionSavingThrowModifier } from './saving-throw-modifier';
import { PropertyDefinitionSkillModifier } from './skill-modifier';
import { PropertyDefinitionSneakAttack } from './sneak-attack';
import { PropertyDefinitionSpeedFactor } from './speed-factor';
import { PropertyDefinitionSpellPower } from './spell-power';
import { PropertyDefinitionSpikeDamage } from './spike-damage';
import { PropertyDefinitionThinker } from './thinker';
import { PropertyDefinitionUnidentified } from './unidentified';
import { PropertyDefinitionVampyre } from './vampyre';
import { PropertyDefinitionWeaponDamageModifier } from './weapon-damage-modifier';

export const PropertyDefinitionSchema = z.discriminatedUnion('type', [
    PropertyDefinitionAbilityCheckModifier,
    PropertyDefinitionAbilityModifier,
    PropertyDefinitionAdvantageAttack,
    PropertyDefinitionAdvantageSavingThrow,
    PropertyDefinitionAilment,
    PropertyDefinitionArmorClassModifier,
    PropertyDefinitionAttackCountModifier,
    PropertyDefinitionAttackModifier,
    PropertyDefinitionCriticalRangeModifier,
    PropertyDefinitionCursed,
    PropertyDefinitionDamageImmunity,
    PropertyDefinitionDamageModifier,
    PropertyDefinitionDamageReduction,
    PropertyDefinitionDamageResistance,
    PropertyDefinitionDamageVulnerability,
    PropertyDefinitionDarkvision,
    PropertyDefinitionDisadvantageAttack,
    PropertyDefinitionDisadvantageSavingThrow,
    PropertyDefinitionEnfeeblement,
    PropertyDefinitionExtraHitpoints,
    PropertyDefinitionExtraWeaponDamageType,
    PropertyDefinitionWeightFactor,
    PropertyDefinitionFeat,
    PropertyDefinitionHealingFactor,
    PropertyDefinitionHealingModifier,
    PropertyDefinitionImmunity,
    PropertyDefinitionLight,
    PropertyDefinitionMaxDexterityBonus,
    PropertyDefinitionProtectionFromSpecie,
    PropertyDefinitionRegeneration,
    PropertyDefinitionSavingThrowModifier,
    PropertyDefinitionSkillModifier,
    PropertyDefinitionSneakAttack,
    PropertyDefinitionSpeedFactor,
    PropertyDefinitionSpellPower,
    PropertyDefinitionSpikeDamage,
    PropertyDefinitionThinker,
    PropertyDefinitionUnidentified,
    PropertyDefinitionVampyre,
    PropertyDefinitionWeaponDamageModifier,
]);

export type Property = z.infer<typeof PropertyDefinitionSchema>;
