// File generated by build-property-programs-index
import { IPropertyProgram } from '../IPropertyProgram';
import { PropertyProgramAilment } from './ailment';
import { PropertyProgramRegeneration } from './regeneration';
import { PropertyProgramVampyre } from './vampyre';

export const PropertyPrograms: Record<string, IPropertyProgram> = {
    PROPERTY_PROGRAM_AILMENT: new PropertyProgramAilment(),
    PROPERTY_PROGRAM_REGENERATION: new PropertyProgramRegeneration(),
    PROPERTY_PROGRAM_VAMPYRE: new PropertyProgramVampyre(),
};
