// File generated by build-effects-index

import { BaseEffectSchema } from '../schemas/BaseEffect';

import z from 'zod';
import { EffectAbilityCheckModifier } from './ability-check-modifier';
import { EffectAbilityModifier } from './ability-modifier';
import { EffectAdvantageAttack } from './advantage-attack';
import { EffectAdvantageSavingThrow } from './advantage-saving-throw';
import { EffectArmorClassModifier } from './armor-class-modifier';
import { EffectAttackCountModifier } from './attack-count-modifier';
import { EffectAttackModifier } from './attack-modifier';
import { EffectBlindness } from './blindness';
import { EffectBreaker } from './breaker';
import { EffectCharm } from './charm';
import { EffectConcentration } from './concentration';
import { EffectCriticalRangeModifier } from './critical-range-modifier';
import { EffectDamageImmunity } from './damage-immunity';
import { EffectDamageModifier } from './damage-modifier';
import { EffectDamageReduction } from './damage-reduction';
import { EffectDamageResistance } from './damage-resistance';
import { EffectDamage } from './damage';
import { EffectDamageVulnerability } from './damage-vulnerability';
import { EffectDarkvision } from './darkvision';
import { EffectDisadvantageAttack } from './disadvantage-attack';
import { EffectDisadvantageSavingThrow } from './disadvantage-saving-throw';
import { EffectDisease } from './disease';
import { EffectEnfeeblement } from './enfeeblement';
import { EffectEnvironment } from './environment';
import { EffectExtraHitpoints } from './extra-hitpoints';
import { EffectFear } from './fear';
import { EffectHealingFactor } from './healing-factor';
import { EffectHealingModifier } from './healing-modifier';
import { EffectHeal } from './heal';
import { EffectImmunity } from './immunity';
import { EffectIncapacity } from './incapacity';
import { EffectInvisibility } from './invisibility';
import { EffectLight } from './light';
import { EffectNegativeLevel } from './negative-level';
import { EffectParalysis } from './paralysis';
import { EffectPetrification } from './petrification';
import { EffectProtectionFromSpecie } from './protection-from-specie';
import { EffectRegenerationSchema } from './regeneration';
import { EffectSavingThrowModifier } from './saving-throw-modifier';
import { EffectSeeInvisibility } from './see-invisibility';
import { EffectSkillModifier } from './skill-modifier';
import { EffectSpeedFactor } from './speed-factor';
import { EffectSpellPower } from './spell-power';
import { EffectSpikeDamage } from './spike-damage';
import { EffectStealth } from './stealth';
import { EffectStun } from './stun';
import { EffectWeaponDamageModifier } from './weapon-damage-modifier';

export const EffectDefinitionSchema = z.discriminatedUnion('type', [
    EffectAbilityCheckModifier,
    EffectAbilityModifier,
    EffectAdvantageAttack,
    EffectAdvantageSavingThrow,
    EffectArmorClassModifier,
    EffectAttackCountModifier,
    EffectAttackModifier,
    EffectBlindness,
    EffectBreaker,
    EffectCharm,
    EffectConcentration,
    EffectCriticalRangeModifier,
    EffectDamageImmunity,
    EffectDamageModifier,
    EffectDamageReduction,
    EffectDamageResistance,
    EffectDamage,
    EffectDamageVulnerability,
    EffectDarkvision,
    EffectDisadvantageAttack,
    EffectDisadvantageSavingThrow,
    EffectDisease,
    EffectEnfeeblement,
    EffectEnvironment,
    EffectExtraHitpoints,
    EffectFear,
    EffectHealingFactor,
    EffectHealingModifier,
    EffectHeal,
    EffectImmunity,
    EffectIncapacity,
    EffectInvisibility,
    EffectLight,
    EffectNegativeLevel,
    EffectParalysis,
    EffectPetrification,
    EffectProtectionFromSpecie,
    EffectRegenerationSchema,
    EffectSavingThrowModifier,
    EffectSeeInvisibility,
    EffectSkillModifier,
    EffectSpeedFactor,
    EffectSpellPower,
    EffectSpikeDamage,
    EffectStealth,
    EffectStun,
    EffectWeaponDamageModifier,
]);

export const EffectSchema = EffectDefinitionSchema.and(BaseEffectSchema);

export type EffectDefinition = z.infer<typeof EffectDefinitionSchema>;
export type Effect = z.infer<typeof EffectSchema>;
