// File generated by build-effects-index

import { BaseEffectSchema } from '../schemas/BaseEffect';

import z from 'zod';
import { EffectAbilityCheckModifier } from './ability-check-modifier';
import { EffectAbilityModifier } from './ability-modifier';
import { EffectRegenerationSchema } from './regeneration';

export const EffectDefinitionSchema = z.discriminatedUnion('type', [
    EffectAbilityCheckModifier,
    EffectAbilityModifier,
    EffectRegenerationSchema,
]);


export const EffectSchema = EffectDefinitionSchema.and(BaseEffectSchema);

export type EffectDefinition = z.infer<typeof EffectSchema>;
export type Effect = z.infer<typeof EffectSchema>;
